spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://EurekaClient
          predicates:
            - Path=/client/test
            - Method=GET
  main:
    web-application-type: reactive

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

server.port: 8765
