spring:
  cloud:
    gateway:
      routes:
        - id: parse
          uri: lb://web-parser
          predicates:
            - Path=/parse
            - Method=POST
        - id: parse-by-parse-info
          uri: lb://web-parser
          predicates:
            - Path=/parse-by-parse-info
            - Method=POST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register:
      with-eureka: true
  instance:
    prefer-ip-address: true

server.port: 8765