spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/price_checker?currentSchema=telegram_service
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          create_namespaces: true
  session:
    jdbc:
      initialize-schema: never

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

server.port: 0
